In [47]:
import pandas as pd 

df = pd.read_csv('students1.csv',index_col=0)
df

      國文   英文  數學  地理   探討
黃旻林   82   76  54  83   77
黃麗美   66   87  61  70   83
王品星  100   71  66  52   73
張慧君   63   68  69  86   82
吳欣書   51   53  73  91   72
昌嘉洋   62   67  93  66   93
翁鈺婷   92  100  65  88   95
吳昕婷   70   82  56  52   60
崔孝憲   91   95  60  54   58
王展人   70   77  71  78   68
謝哲維   85   94  55  99   93
馮淑芬   88   86  86  70   67
蔡明平   81   50  88  76   98
蔡孟泉   83   62  73  53   63
魏秋萍   93   75  75  99   59
林群清   59   53  83  95   72
王柏聖   68   89  70  98   57
元延辛   85   81  75  80   97
白世宏   59   91  94  87   78
余宗儒   71   53  75  66   84
黃心航   87   87  65  54  100
艾巧夫   54   86  71  54   69
邱亭君   74   59  78  68   82
賴佳雯   85   88  67  84   51
陳嘉淑   93   95  88  54   65
劉雯芬   87   69  86  90   70
黃名明   55   94  78  77   66
楊綺芬  100   76  61  89   76
王德城   73   99  99  87   92
方雅慧   92   67  81  71   93
黃雅慧   61   71  52  64   92
陳姵彬   88   69  77  55   95
杜儀鳳   60   89  81  88   52
郭致恬   65   91  82  80   96
周怡啟   54   73  96  56   73
賴又琦   95  100  96  83   92
唐雪豪   97   72  78  66   87
張俊傑   61   58  80  63   69
王雅慧   90   77  84  90   88
黎惠雯   91   55  71  63   93
葉軍仰   76   76  85  91   86
鄭琇亞   61   96  64  73   57
戴萱能   53   71  66  70   90
羅幸娥  100   96  95  96   98
劉林中   68   52  60  56   73
趙家豪   63   59  79  97   69
謝貞妃   67   84  83  71   78
黃善迪   77   53  51  65   77
吳淑惠   57   62  98  59   59
郭淑枝   72   83  65  58   99

In [48]:
import pandas as pd 

df = pd.read_csv('students1.csv',index_col=0)

df['國文'] # series
type(df[['國文','數學']]) # dataframe

pandas.core.frame.DataFrame

In [49]:
df.loc['黃善迪']
df.loc[['黃善迪','謝貞妃']]

     國文  英文  數學  地理  探討
黃善迪  77  53  51  65  77
謝貞妃  67  84  83  71  78

In [50]:
df.iloc[0]
df.iloc[[0,3]]

     國文  英文  數學  地理  探討
黃旻林  82  76  54  83  77
張慧君  63  68  69  86  82

In [51]:
df.loc['周怡啟':'吳淑惠']

      國文   英文  數學  地理  探討
周怡啟   54   73  96  56  73
賴又琦   95  100  96  83  92
唐雪豪   97   72  78  66  87
張俊傑   61   58  80  63  69
王雅慧   90   77  84  90  88
黎惠雯   91   55  71  63  93
葉軍仰   76   76  85  91  86
鄭琇亞   61   96  64  73  57
戴萱能   53   71  66  70  90
羅幸娥  100   96  95  96  98
劉林中   68   52  60  56  73
趙家豪   63   59  79  97  69
謝貞妃   67   84  83  71  78
黃善迪   77   53  51  65  77
吳淑惠   57   62  98  59  59

In [52]:
df.iloc[0:3]

      國文  英文  數學  地理  探討
黃旻林   82  76  54  83  77
黃麗美   66  87  61  70  83
王品星  100  71  66  52  73

In [53]:
df.head()
df.loc['黃麗美','地理']=61
df.head()

      國文  英文  數學  地理  探討
黃旻林   82  76  54  83  77
黃麗美   66  87  61  61  83
王品星  100  71  66  52  73
張慧君   63  68  69  86  82
吳欣書   51  53  73  91  72

In [54]:
df[:10]

      國文   英文  數學  地理  探討
黃旻林   82   76  54  83  77
黃麗美   66   87  61  61  83
王品星  100   71  66  52  73
張慧君   63   68  69  86  82
吳欣書   51   53  73  91  72
昌嘉洋   62   67  93  66  93
翁鈺婷   92  100  65  88  95
吳昕婷   70   82  56  52  60
崔孝憲   91   95  60  54  58
王展人   70   77  71  78  68

In [55]:
df[-10:]

      國文  英文  數學  地理  探討
葉軍仰   76  76  85  91  86
鄭琇亞   61  96  64  73  57
戴萱能   53  71  66  70  90
羅幸娥  100  96  95  96  98
劉林中   68  52  60  56  73
趙家豪   63  59  79  97  69
謝貞妃   67  84  83  71  78
黃善迪   77  53  51  65  77
吳淑惠   57  62  98  59  59
郭淑枝   72  83  65  58  99

In [93]:

df['國文'] + df['英文'] + df['地理'] + df['數學'] + df['探討']

黃旻林    372
黃麗美    358
王品星    362
張慧君    368
吳欣書    340
昌嘉洋    381
翁鈺婷    440
吳昕婷    320
崔孝憲    358
王展人    364
謝哲維    426
馮淑芬    397
蔡明平    393
蔡孟泉    334
魏秋萍    401
林群清    362
王柏聖    382
元延辛    418
白世宏    409
余宗儒    349
黃心航    393
艾巧夫    334
邱亭君    361
賴佳雯    375
陳嘉淑    395
劉雯芬    402
黃名明    370
楊綺芬    402
王德城    450
方雅慧    404
黃雅慧    340
陳姵彬    384
杜儀鳳    370
郭致恬    414
周怡啟    352
賴又琦    466
唐雪豪    400
張俊傑    331
王雅慧    429
黎惠雯    373
葉軍仰    414
鄭琇亞    351
戴萱能    350
羅幸娥    485
劉林中    309
趙家豪    367
謝貞妃    383
黃善迪    323
吳淑惠    335
郭淑枝    377
dtype: int64

In [90]:
stu_sum = df.sum(axis=1)
stu_mean = stu_sum / 5.0

In [91]:
df['總分'] = stu_sum
df['平均'] = stu_mean

In [92]:
df

      國文   英文  數學  地理   探討          總分          平均
黃旻林   82   76  54  83   77  3693.93024  738.786048
黃麗美   66   87  61  61   83  3554.91136  710.982272
王品星  100   71  66  52   73  3594.63104  718.926208
張慧君   63   68  69  86   82  3654.21056  730.842112
吳欣書   51   53  73  91   72  3376.17280  675.234560
昌嘉洋   62   67  93  66   93  3783.29952  756.659904
翁鈺婷   92  100  65  88   95  4369.16480  873.832960
吳昕婷   70   82  56  52   60  3177.57440  635.514880
崔孝憲   91   95  60  54   58  3554.91136  710.982272
王展人   70   77  71  78   68  3614.49088  722.898176
謝哲維   85   94  55  99   93  4230.14592  846.029184
馮淑芬   88   86  86  70   67  3942.17824  788.435648
蔡明平   81   50  88  76   98  3902.45856  780.491712
蔡孟泉   83   62  73  53   63  3316.59328  663.318656
魏秋萍   93   75  75  99   59  3981.89792  796.379584
林群清   59   53  83  95   72  3594.63104  718.926208
王柏聖   68   89  70  98   57  3793.22944  758.645888
元延辛   85   81  75  80   97  4150.70656  830.141312
白世宏   59   91  94  87   78  4061.33728  812.267456
余宗儒   71   53  75  66   84  3465.54208  693.108416
黃心航   87   87  65  54  100  3902.45856  780.491712
艾巧夫   54   86  71  54   69  3316.59328  663.318656
邱亭君   74   59  78  68   82  3584.70112  716.940224
賴佳雯   85   88  67  84   51  3723.72000  744.744000
陳嘉淑   93   95  88  54   65  3922.31840  784.463680
劉雯芬   87   69  86  90   70  3991.82784  798.365568
黃名明   55   94  78  77   66  3674.07040  734.814080
楊綺芬  100   76  61  89   76  3991.82784  798.365568
王德城   73   99  99  87   92  4468.46400  893.692800
方雅慧   92   67  81  71   93  4011.68768  802.337536
黃雅慧   61   71  52  64   92  3376.17280  675.234560
陳姵彬   88   69  77  55   95  3813.08928  762.617856
杜儀鳳   60   89  81  88   52  3674.07040  734.814080
郭致恬   65   91  82  80   96  4110.98688  822.197376
周怡啟   54   73  96  56   73  3495.33184  699.066368
賴又琦   95  100  96  83   92  4627.34272  925.468544
唐雪豪   97   72  78  66   87  3971.96800  794.393600
張俊傑   61   58  80  63   69  3286.80352  657.360704
王雅慧   90   77  84  90   88  4259.93568  851.987136
黎惠雯   91   55  71  63   93  3703.86016  740.772032
葉軍仰   76   76  85  91   86  4110.98688  822.197376
鄭琇亞   61   96  64  73   57  3485.40192  697.080384
戴萱能   53   71  66  70   90  3475.47200  695.094400
羅幸娥  100   96  95  96   98  4816.01120  963.202240
劉林中   68   52  60  56   73  3068.34528  613.669056
趙家豪   63   59  79  97   69  3644.28064  728.856128
謝貞妃   67   84  83  71   78  3803.15936  760.631872
黃善迪   77   53  51  65   77  3207.36416  641.472832
吳淑惠   57   62  98  59   59  3326.52320  665.304640
郭淑枝   72   83  65  58   99  3743.57984  748.715968